### ISSUE TITLE
FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW

### ISSUE THREAD

**Issue by rubic0nexe** [xmrig/xmrig#1973]
FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW

What is this and how do i fix that?

**Comment by SChernykh** [comment]
You need to run as administrator/root to enable MSR. You can read more here: https://xmrig.com/docs/miner/randomx-optimization-guide/msr

**Comment by mascondante** [comment]
I'm getting this error and I am running with administrative permissions. No events in my AV. 
![image](https://user-images.githubusercontent.com/2492044/103075512-c3124780-4599-11eb-83d7-ed95ccf0e252.png)

**Comment by theSchein** [comment]
I too am having this issue. Running as root

**Comment by tom634** [comment]
I too am having this issue. Running as administrator

**Comment by SChernykh** [comment]
Please provide the full console output of XMRig when it starts

**Comment by tom634** [comment]
![obraz](https://user-images.githubusercontent.com/24915307/104322753-980a7c00-54e5-11eb-85f0-80d52e121594.png)
My console output

**Comment by SChernykh** [comment]
You are not running it as administrator.

**Comment by tom634** [comment]
I run as administrator and it worked, thanks

**Comment by iZerox7** [comment]
When i open as Administrator (Intel, win 10), it no works

**Comment by iZerox7** [comment]
> When i open as Administrator (Intel, win 10), it no works
> Edit: It says "pause", press any key to continue and when i press any key it closes

# #
![Uploading 20210123_123354.jpg…]()

**Comment by melkorex** [comment]
Hi i have same issue runing admin mode.

` * ABOUT        XMRig/6.7.2 MSVC/2019
 * LIBS         libuv/1.40.0 OpenSSL/1.1.1i hwloc/2.4.0
 * HUGE PAGES   permission granted
 * 1GB PAGES    unavailable
 * CPU          Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (1) 64-bit AES VM
                L2:1.0 MB L3:8.0 MB 4C/8T NUMA:1
 * MEMORY       11.4/15.9 GB (71%)
 * DONATE       5%
 * ASSEMBLY     auto:intel
 * POOL #1      pool.minexmr.com:4444 algo auto
 * COMMANDS     hashrate, pause, resume, results, connection
 * OPENCL       disabled
 * CUDA         disabled
[2021-01-28 12:33:40.199]  net      use pool pool.minexmr.com:4444  37.59.43.131
[2021-01-28 12:33:40.199]  net      new job from pool.minexmr.com:4444 diff 75000 algo rx/0 height 2284462
[2021-01-28 12:33:40.200]  cpu      use argon2 implementation AVX2
[2021-01-28 12:33:40.204]  msr      cannot set MSR 0x000001a4 to 0x0000000f
[2021-01-28 12:33:40.242]  msr      FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
[2021-01-28 12:33:40.243]  randomx  init dataset algo rx/0 (8 threads) seed f1a94ed2953f45f4...
[2021-01-28 12:33:40.310]  randomx  allocated 2336 MB (2080+256) huge pages 0% 0/1168 +JIT (66 ms)
[2021-01-28 12:33:45.997]  randomx  dataset ready (5686 ms)
[2021-01-28 12:33:45.997]  cpu      use profile  rx  (4 threads) scratchpad 2048 KB
[2021-01-28 12:33:46.000]  cpu      READY threads 4/4 (4) huge pages 100% 4/4 memory 8192 KB (2 ms)`

**Comment by SChernykh** [comment]
```CPU Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (1) 64-bit AES VM```
The `VM` part says that you're running it inside a virtual machine. MSR mod works only on the physical CPU.

**Comment by melkorex** [comment]
> 
> 
> `CPU Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (1) 64-bit AES VM`
> The `VM` part says that you're running it inside a virtual machine. MSR mod works only on the physical CPU.

Nop, is directly from cmd of my physical computer but i have running 4 docker working, i think that is the problem.... but its a shame

**Comment by iZerox7** [comment]
I fix it 
You will have to open it frim CMD
First, You have to open cmd as Administrator, then open the dkrectory in cmd (always with CD at begining) and finally open the file
It works for me

**Comment by SChernykh** [comment]
It will never say `VM` on physical computer, double check where you start it from.

**Comment by melkorex** [comment]
Come on, @SChernykh  i know the first questions is your turn off and on your computer.... but its not my case pls.

![Captura de pantalla 2021-01-28 124901](https://user-images.githubusercontent.com/46333033/106163088-8bce2200-6167-11eb-94dc-9c2e34fc550d.jpg)

Its not running in docker is my windows CMD of physical pc.

**Comment by SChernykh** [comment]
XMRig checks the hypervisor bit in CPUID and if it's set, it shows "VM". This bit is never set on a physical CPU which means your whole Windows is running inside a VM right now. Probably because of docker or some other software you installed. MSR mod won't work until you fix it.

**Comment by melkorex** [comment]
@SChernykh ok its say it in my physical computer.... for what ? i dont know.... later i turno off all of docker services and docker containers and try again, if i don see VM i upload the image to check the code. Thanks

**Comment by melkorex** [comment]
I dont know its usefull for you.

![Captura de pantalla 2021-01-28 124901](https://user-images.githubusercontent.com/46333033/106167199-bc17bf80-616b-11eb-8ad3-ea8babe21682.jpg)

`wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed, status`

inform no VM

but down exec start.cmd xmrig

VM.

......

**Comment by ShadyJay1979** [comment]
Shut down NiceHash Miner and right click it and run as Administrator

**Comment by guru220011** [comment]
Hey guys, make sure you Right Click and Run as Administrator on the file itself in the folder and not on the shortcut that it creates.

**Comment by ScardracS** [comment]
On latest build i have same problem (v6.8.1) while on 6.8.0 haven't any issue (windows 10 enterprise LTSC with amd ryzen). I have run as administrator, reboot and rerun as administrator but nothing

**Comment by 1RedOne** [comment]
If you've got Docker and clicked 'next, next, next, finish' through the wizard, you probably setup Hyper-V.  

Once you setup hyper-v your host partition is, in some ways, treated as a VM too.  This impacts how you interact with the physical hardware on the device.

Basically you're effectively running as a VM.

**Comment by Shahnewaz1996** [comment]
> I'm getting this error and I am running with administrative permissions. No events in my AV.
> ![image](https://user-images.githubusercontent.com/2492044/103075512-c3124780-4599-11eb-83d7-ed95ccf0e252.png)

I fixed this by finding it under Process Hacker's Services tab, and manually editing the service's path (WinRing0 Driver).
I pointed it to XMRig's driver location, and it deleted the service afterwards.
> Come on, @SChernykh i know the first questions is your turn off and on your computer.... but its not my case pls.
> 
> ![Captura de pantalla 2021-01-28 124901](https://user-images.githubusercontent.com/46333033/106163088-8bce2200-6167-11eb-94dc-9c2e34fc550d.jpg)
> 
> Its not running in docker is my windows CMD of physical pc.

See my comment here: https://github.com/xmrig/xmrig/issues/1891#issuecomment-776180629

**Comment by TowrArisu** [comment]
My machine had the same problem with failing to apply the MSR Mod and also showed  "VM" although it was not a VM.
I found a setting in the Bios with regards to  Intel Virtualization Technology, I switched it off and now the problem is gone.
VM no longer shows and MSR is set successfully.

**Comment by MacZillions** [comment]
> Hey guys, make sure you Right Click and Run as Administrator on the file itself in the folder and not on the shortcut that it creates.

It works. 🤜🤛

**Comment by june-lau** [comment]
I'm getting this error and I am running with administrative permissions. (platform: laptop, win10)
I need your help.
![1](https://user-images.githubusercontent.com/79624967/109112494-be266b80-7775-11eb-8cf1-bbfbc5bbbcf6.jpg)

**Comment by SChernykh** [comment]
Try to reboot and don't start that program before xmrig (`Program Files (x86)\kaying_tools\program\colligatetest\masterluo`).

**Comment by mightmay** [comment]
Hi, how can I run as admin in linux ?
Is this the correct command ?   sudo ./xmrig

**Comment by june-lau** [comment]
> 尝试重新启动，不要在xmrig（`Program Files (x86)\kaying_tools\program\colligatetest\masterluo`）之前启动该程序。

Thank you, sir.

**Comment by esskayesss** [comment]
> Hi, how can I run as admin in linux ?
> Is this the correct command ?
> sudo ./xmrig

yes that should work. If you're using a configuration file, you'll now have to pass it with the `-c /path/to/config` option

**Comment by cuppajoeman** [comment]
> > Hi, how can I run as admin in linux ?
> > Is this the correct command ?
> > sudo ./xmrig
> 
> yes that should work. If you're using a configuration file, you'll now have to pass it with the `-c /path/to/config` option

Verified, it works.

**Comment by mightmay** [comment]
> > > Hi, how can I run as admin in linux ?
> > > Is this the correct command ?
> > > sudo ./xmrig
> > 
> > 
> > yes that should work. If you're using a configuration file, you'll now have to pass it with the `-c /path/to/config` option
> 
> Verified, it works.

Thank You, I was sure that is the correct command, however, I am still getting this error on my Ubuntu 20:
FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
I also tried running this command: sudo bash ./scripts/randomx_boost.sh
However, I am getting the error:
`line 26: wrmsr: command not found`

**Comment by esskayesss** [comment]
> > > > Hi, how can I run as admin in linux ?
> > > > Is this the correct command ?
> > > > sudo ./xmrig
> > > 
> > > 
> > > yes that should work. If you're using a configuration file, you'll now have to pass it with the `-c /path/to/config` option
> > 
> > Verified, it works.
> 
> Thank You, I was sure that is the correct command, however, I am still getting this error on my Ubuntu 20:
> FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
> I also tried running this command: sudo bash ./scripts/randomx_boost.sh
> However, I am getting the error:
> `line 26: wrmsr: command not found`
> 
> 

You probably have to install `wrmsr`. On Ubuntu I think it's the `msr-tools` package.

**Comment by freki12** [comment]
Personally I've had some issues getting windows to start xmrig in admin mode when starting from a .cmd or .bat so if you're using this method instead of config file try:
Right clicking -> Properties -> Check Run in Administrator mode on xmrig.exe - solved all my issues.

**Comment by mightmay** [comment]
> > > > > Hi, how can I run as admin in linux ?
> > > > > Is this the correct command ?
> > > > > sudo ./xmrig
> > > > 
> > > > 
> > > > yes that should work. If you're using a configuration file, you'll now have to pass it with the `-c /path/to/config` option
> > > 
> > > 
> > > Verified, it works.
> > 
> > 
> > Thank You, I was sure that is the correct command, however, I am still getting this error on my Ubuntu 20:
> > FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
> > I also tried running this command: sudo bash ./scripts/randomx_boost.sh
> > However, I am getting the error:
> > `line 26: wrmsr: command not found`
> 
> You probably have to install `wrmsr`. On Ubuntu I think it's the `msr-tools` package.

Thank You, you are correct.
I was able to fix this error by install wrmsr with this command:
`apt-get install msr-tools`
However, now I am getting this error instead, when I tried to run: `sudo bash ./scripts/randomx_boost.sh`
I get this error:  `wrmsr: CPU 0 cannot set MSR 0x000001a4 to 0x000000000000000f`

**Comment by esskayesss** [comment]
> However, now I am getting this error instead, when I tried to run: `sudo bash ./scripts/randomx_boost.sh`
> I get this error:  `wrmsr: CPU 0 cannot set MSR 0x000001a4 to 0x000000000000000f`
> 
Can you post the entire output? Does it detect a proper architecture cpu?

**Comment by tsumeone** [comment]
For anyone saying their CPU is showing VM but they are not running in a VM:  The Windows security feature Core Isolation - Memory Integrity will cause this.  That is because the way it works is to essentially run the entire OS inside a VM.

**Comment by chrisdab** [comment]
The Core Isolation security setting in windows 10 caused the same issue for me as not running in administrative mode, although when not running in admin mode the error message correctly told me I wasn't in admin mode. I turned on Core Isolation recently and had my hashrate dropped, with the error message that brought me to this thread.

**Comment by DeeDeeRanged** [comment]
> > > > > > Hi, how can I run as admin in linux ?
> > > > > > Is this the correct command ?
> > > > > > sudo ./xmrig
> > > > > 
> > > > > 
> > > > > yes that should work. If you're using a configuration file, you'll now have to pass it with the `-c /path/to/config` option
> > > > 
> > > > 
> > > > Verified, it works.
> > > 
> > > 
> > > Thank You, I was sure that is the correct command, however, I am still getting this error on my Ubuntu 20:
> > > FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
> > > I also tried running this command: sudo bash ./scripts/randomx_boost.sh
> > > However, I am getting the error:
> > > `line 26: wrmsr: command not found`
> > 
> > 
> > You probably have to install `wrmsr`. On Ubuntu I think it's the `msr-tools` package.
> 
> Thank You, you are correct.
> I was able to fix this error by installing `wrmsr `with this command:
> `apt-get install msr-tools`
> However, now I am getting this error instead, when I tried to run: `sudo bash ./scripts/randomx_boost.sh`
> I get this error: `wrmsr: CPU 0 cannot set MSR 0x000001a4 to 0x000000000000000f`

Strange you had to install msr-tools. I am running Debian bullseye/testing,  Ryzen 7 5800x getting a nice 9270.9 H/s algo rx/0,  Only thing I had to do was was using sudo to get it working as required.

**Comment by ParveenBhadooOfficial** [comment]
It'll not run MSR MOD on VPS Right?

**Comment by FSPinho** [comment]
For anyone having it on Ubuntu, I fixed it by:
- Installing msr-tools with `apt-get install msr-tools`;
- Disabling secure boot;
- And then running as root `sudo xmrig ...`

**Comment by DeeDeeRanged** [comment]
> For anyone having it on Ubuntu, I fixed it by:
> 
>     * Installing msr-tools with `apt-get install msr-tools`;
> 
>     * Disabling secure boot;
> 
>     * And then running as root `sudo xmrig ...`

You don't need to run xmrig as root.
Download or copy the script randomx_boost.sh from https://github.com/xmrig/xmrig/scripts run that with sudo/root change to lines in the config.json file "rdmsr": false and "wrmsr": false to stop it blabbering about msr start it as user xmrig. As this is much safer.

**Comment by Eduarrb** [comment]
> I fix it
> You will have to open it frim CMD
> First, You have to open cmd as Administrator, then open the dkrectory in cmd (always with CD at begining) and finally open the file
> It works for me

I works!!! thanks

**Comment by bktcaery** [comment]
> For anyone having it on Ubuntu, I fixed it by:
> 
>     * Installing msr-tools with `apt-get install msr-tools`;
> 
>     * Disabling secure boot;
> 
>     * And then running as root `sudo xmrig ...`

Thanks, works great.

**Comment by Hotrod369** [comment]
> The Core Isolation security setting in windows 10 caused the same issue for me as not running in administrative mode, although when not running in admin mode the error message correctly told me I wasn't in admin mode. I turned on Core Isolation recently and had my hashrate dropped, with the error message that brought me to this thread.

![image](https://user-images.githubusercontent.com/72291352/139732566-049b5401-0bbb-49d7-9e7c-9e7e99aed7f1.png)
chrisdab you're exactly right. I turned off core isolation and I still get VM instead of AES but the Failed to apply MSR mod error is gone.

**Comment by NewSunSEO** [comment]
> 
> 
> For anyone having it on Ubuntu, I fixed it by:
> 
>     * Installing msr-tools with `apt-get install msr-tools`;
> 
>     * Disabling secure boot;
> 
>     * And then running as root `sudo xmrig ...`

THANK YOU!!!  I am new to Linux & that fixed the MSR for me.  I was looking for HOURS!!!

**Comment by ksgnu** [comment]
> > For anyone having it on Ubuntu, I fixed it by:
> > ```
> > * Installing msr-tools with `apt-get install msr-tools`;
> > 
> > * Disabling secure boot;
> > 
> > * And then running as root `sudo xmrig ...`
> > ```
> 
> THANK YOU!!! I am new to Linux & that fixed the MSR for me. I was looking for HOURS!!!

Worked for me too, thanks a lot!

**Comment by netcast22** [comment]
> > > For anyone having it on Ubuntu, I fixed it by:
> > > ```
> > > * Installing msr-tools with `apt-get install msr-tools`;
> > > 
> > > * Disabling secure boot;
> > > 
> > > * And then running as root `sudo xmrig ...`
> > > ```
> > 
> > 
> > THANK YOU!!! I am new to Linux & that fixed the MSR for me. I was looking for HOURS!!!
> 
> Worked for me too, thanks a lot!

> Works like a charm!

**Comment by Soggydan** [comment]
If you are a windows user check here for 5 fixes to try
[https://www.home-mining.com/failed-to-apply-msr-mod-hashrate-will-be-low/](url)

**Comment by SteaceP** [comment]
The only thing that worked for me was to disable SMT (virtualization) in bios... Was doing this on a clean Windows 11 install. No Hyper-V, no WSL, no shit!

**Comment by Rakshitha-M-Rodrigo** [comment]
running with sudo or  the super user mode worked for me. Thanks.

**Comment by sapeg** [comment]
Hi. I have a ryzen 5 3600, Linux OS. There is virtualization support, but it is disabled in the bios. I go under the root in the console, run from the directory where the program is located: xmrig -t 6 -o pool.minexmr.com:4444... But I still get the message: msr kernel module is not available, FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW. 
   What other options are there?

**Comment by juroberttyb** [comment]
These steps help me on ubuntu 22.04
1, Disable secure boot
2, Reboot
3, Run xmrig as root

**Comment by umeshlab** [comment]
> You need to run as administrator/root to enable MSR. You can read more here: https://xmrig.com/docs/miner/randomx-optimization-guide/msr


Thanks a lot it helped me.

**Comment by furic** [comment]
Disabled secure boot and run with admin in Windows, still no luck for me...

CPU: Intel i7 10th Gen 10750H @ 2.60GHz
OS: Windows 11 Home

**Comment by Egemenbdk** [comment]
I FOUND OUT HOW TO FIX IT COMPLETELY!

1. Go into BIOS mode. (search up on google how to go in BIOS mode on your motherboard/laptop)
2. Disable Intel VTD and Intel VTX. If you only have one, just disable that one.
3. Save and exit, start your computer.
4. Run cmd as admin
5. Type "cd C:\Users\YOUR_NAME_HERE\Downloads\xmrig-6.19.2-gcc-win64\xmrig-6.19.2" OR wherever your file is located.
6. Then type xmrig.exe into the cmd.

**Comment by EMPTY754** [comment]
Buy another motherboard.

**Comment by NorthScholar** [comment]
Im having this issue too, i right click and select run as administrator..what to do excatly=?
![Uten navn](https://github.com/xmrig/xmrig/assets/160160271/8988bb1b-f6d1-4f51-a5b5-9c41bac5b2c4)

**Comment by SChernykh** [comment]
Did you try other advices from this thread? Secure boot disabled?

**Comment by NorthScholar** [comment]
I tried what i understand :)
I dont know how to: Installing msr-tools with `apt-get install msr-tools, i will keep reading a bit

**Comment by SChernykh** [comment]
`apt-get install msr-tools`
This is not for Windows

**Comment by NorthScholar** [comment]
Where or how do i use it? Do i write in the "extra parameters"?

**Comment by SChernykh** [comment]
You just don't use it on Windows. You should try to disable any memory integrity, secure boot, virtualization options you can find in BIOS and in Windows.

**Comment by NorthScholar** [comment]
Ok, thanks - i have not checked my BIOS yet. i will do that now next

**Comment by jsalaz-Gramps** [comment]
Turning off Memory integrity is worrisome, since shortly after I mpoved the switch to disabled, 64 detectio0ns from Malwarebytes had to be cleaned.  I will use it, to get the MSR tweak, but that's it.  I really does not improve performance on this computer of mine.  HP Pavillion CX with AMD Ryzen 7.

I will be getting the AISC USB sticks on Amazon, with an associated power strip soon.  It's all I can afford due to financial restraints.

**Comment by anickname028** [comment]
i've followed everything above and still nothing. 
disabled secure boot
disabled virtualization
after all that no MSR mod (it fails)

**Comment by jsalaz-Gramps** [comment]
When you right click on the xmrig.exe file, does it say Unblock? If ti does, Unblock it. It's very picky.

**Comment by anickname028** [comment]
no unblock button, just properties settings, probably because i unzipped the file.
also running the benchmarks that came with it

**Comment by jsalaz-Gramps** [comment]
OK, the unblock is under properties. It should be in the lower half on the right. Unzipping doesn't cause the files to break, but it makes everything accessible. The same goes for benchmarking. No issues with that either.

**Comment by jsalaz-Gramps** [comment]
OH, I forgot to ask what version of Windows 11 do you have?

**Comment by jsalaz-Gramps** [comment]
Hoepfully my previous comment about the Unblock being under properties is going to work. I have a script that I can send, that will manually unlock the MSR addresses. It works, but will still show the MSR Mod not applying, but it will when you run the batch file.

**Comment by jsalaz-Gramps** [comment]
Did it work?

**Comment by Fgr-35** [comment]
Is there a way to apply msr mod on a .cmd file? I couldn't get xmrig to connect with the pool so i made a .cmd file provided by the pool to start but i cannot run it in admin mode so i won't get msr. How can i fix that?

**Comment by yashatkare** [comment]
Please help me with this, i am using ubuntu 22 not an VM, FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW


`* ABOUT        XMRig/6.21.3 gcc/11.4.0 (built for Linux x86-64, 64 bit)
 * LIBS         libuv/1.48.0 OpenSSL/3.0.13 hwloc/2.10.0
 * HUGE PAGES   supported
 * 1GB PAGES    disabled
 * CPU          11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz (1) 64-bit AES
                L2:4.0 MB L3:16.0 MB 8C/16T NUMA:1
 * MEMORY       2.3/31.2 GB (7%)
                Controller0-ChannelA-DIMM0: <empty>
                Controller0-ChannelA-DIMM1: 32 GB DDR4 @ 3200 MHz CT32G4DFD832A.M16FF 
                Controller0-ChannelB-DIMM0: <empty>
                Controller0-ChannelB-DIMM1: <empty>
 * MOTHERBOARD  ASUSTeK COMPUTER INC. - PRIME B560M-A
 * DONATE       1%
 * ASSEMBLY     auto:intel
 * POOL #1      xmr-asia1.nanopool.org:14433 coin Monero
 * COMMANDS     hashrate, pause, resume, results, connection
 * OPENCL       disabled
 * CUDA         12.2/12.2/6.21.1
 * NVML         12.535.183.01/535.183.01 press e for health report
 * CUDA GPU     #0 01:00.0 NVIDIA GeForce RTX 3050 1792/7001 MHz smx:20 arch:86 mem:7585/7970 MB
[2024-06-27 11:23:12.308]  net      use pool xmr-asia1.nanopool.org:14433 TLSv1.3 51.79.145.144
[2024-06-27 11:23:12.308]  net      fingerprint (SHA-256): "c38886efdee542ebd99801b75c75d3498d97978bbcdec07c7271cb19729e014f"
[2024-06-27 11:23:12.308]  net      new job from xmr-asia1.nanopool.org:14433 diff 480045 algo rx/0 height 3180275 (42 tx)
[2024-06-27 11:23:12.308]  cpu      use argon2 implementation AVX-512F
[2024-06-27 11:23:12.308]  msr      cannot set MSR 0x000001a4 to 0x000000000000000f
[2024-06-27 11:23:12.308]  msr      FAILED TO APPLY MSR MOD, HASHRATE WILL BE LOW
[2024-06-27 11:23:12.308]  randomx  init dataset algo rx/0 (16 threads) seed f97b3d9f5db1f3fc...
[2024-06-27 11:23:12.598]  randomx  allocated 2336 MB (2080+256) huge pages 100% 1168/1168 +JIT (2`

**Comment by ImTand** [comment]
Sorry, I know I'm about 4 years late lol. In your BIOS (if you're using an AMD CPU) there should be a setting called SVM. If not, search for virtualization. In my BIOS I found this setting under the "Advanced" tab, then CPU Configuration, and then SVM Mode. I believe that it has a different name if you're using an Intel CPU but the process should be mostly the same.

Make sure you have SVM or any CPU Virtualization **OFF.** Then, once it is off, you should be able to run the command prompt as an administrator and start your XMRig through there. This doubled to tripled my hashrates, so I hope this works for you all!

**Comment by jsalaz-Gramps** [comment]
Thank you!

**Comment by TheSeer507** [comment]
> I FOUND OUT HOW TO FIX IT COMPLETELY!
> 
> 
> 
> 1. Go into BIOS mode. (search up on google how to go in BIOS mode on your motherboard/laptop)
> 
> 2. Disable Intel VTD and Intel VTX. If you only have one, just disable that one.
> 
> 3. Save and exit, start your computer.
> 
> 4. Run cmd as admin
> 
> 5. Type "cd C:\Users\YOUR_NAME_HERE\Downloads\xmrig-6.19.2-gcc-win64\xmrig-6.19.2" OR wherever your file is located.
> 
> 6. Then type xmrig.exe into the cmd.

This work for me, Intel i7 processor on a HP ZBook laptop. Both options where present turned off both, hash rate when 3x.

**Comment by SChernykh** [comment]
BIOS updates reset all settings. You need to disable virtualization in BIOS again.

**Comment by satyadvi** [comment]
msr mod is not getting unabled , i did a bios update and not its not just working.  moreover i'm using OMEN GAMING LAPTOP , can't even access proper bios , what to do??

**Comment by kelno** [comment]
Disabling SVM in bios did fix it for me.
